name = "Contree2"
author = "MmeCromatique"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43b0a08cddc135fd9d1558e30a537e8da0e39dc89b7129e5f038e6121d7ee642"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
unsup = "1.1.6"
